name: models
description: "A new Flutter package project."
publish_to: 'none'
version: 0.0.1


environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.2.1
  table_calendar: ^3.0.8
  lottie: ^3.1.2
  dio: ^5.4.3
  rating_dialog: ^2.0.4
  shared_preferences: ^2.0.15
  provider: ^6.0.4
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^6.2.1

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icons/faviconColor.png"